// Auto-generated by v3 builder
export type BrandMeta = {
  name: string;
  slug?: string;
  domain?: string;
};

export const BRANDS: BrandMeta[] = [
  { name: "Logo", slug: "logo", domain: undefined },
  { name: "Placeholder", slug: "placeholder", domain: undefined }
];

const simpleIcon = (slug: string) =>
  `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug.toLowerCase()}.svg`;

const clearbitLogo = (domain: string) =>
  `https://logo.clearbit.com/${domain}`;

export const buildLogoUrls = (brand: BrandMeta) => {
  const urls: string[] = [];
  // Prefer Clearbit first for better coverage; then Simple Icons
  if (brand.domain) urls.push(clearbitLogo(brand.domain));
  if (brand.slug) urls.push(simpleIcon(brand.slug));
  return urls;
};
